services:
  - type: web
    name: ecommerce-order-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false
    healthCheckPath: /
    autoDeploy: true
    plan: starter
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
